version: "3"

services:
  bitcoind:
    restart: unless-stopped
    build:
      context: ./Dockerfiles
      dockerfile: bitcoin
    environment:
      BITCOIN_NETWORK: mainnet
    user: root:root
    command:
      - bitcoind
      - -datadir=/data
      - -rpcauth=${BITCOIND_RPC_AUTH}
      - -rpcport=43782
      - -rpcbind=0.0.0.0:43782
      - -rpcallowip=0.0.0.0/0
      - -port=39388
      - -txindex=1
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -zmqpubrawtx=tcp://0.0.0.0:28333
      - -deprecatedrpc=signrawtransaction
      - -assumevalid=0000000000000000000f1c54590ee18d15ec70e68c8cd4cfbadb1b4f11697eee
    ports:
      - "43782:43782"
    expose:
      - "43782" # RPC
      - "39388" # P2P
      - "28332" # ZMQ
      - "28333" # ZMQ
    volumes:
      - "${DATADIR_ROOT}/.bitcoin:/data"

  eclair:
    restart: unless-stopped
    stop_signal: SIGINT
    image: acinq/eclair:btcpay
    environment:
      JAVA_OPTS: |
        -Xmx256m
        -Declair.printToConsole
        -Declair.headless
        -Declair.chain=mainnet
        -Declair.server.binding-ip=0.0.0.0
        -Declair.server.public-ips.0=13.78.33.133
        -Declair.server.port=9876
        -Declair.api.enabled=true
        -Declair.api.binding-ip=0.0.0.0
        -Declair.api.port=8080
        -Declair.node-alias=jem2323-eclair1
        -Declair.api.password=${ECLAIR_API_PASS}
        -Declair.bitcoind.host=bitcoind
        -Declair.bitcoind.rpcport=43782
        -Declair.bitcoind.rpcuser=${BITCOIND_RPC_USER}
        -Declair.bitcoind.rpcpassword=${BITCOIND_RPC_PASS}
        -Declair.bitcoind.zmqblock=tcp://bitcoind:28332
        -Declair.bitcoind.zmqtx=tcp://bitcoind:28333
    expose:
      - "9876" # server port
      - "8080" # api port
    volumes:
      - "${DATADIR_ROOT}/.bitcoin:/etc/bitcoin"
      - "${DATADIR_ROOT}/.eclair:/data"
    links:
      - bitcoind

  nbxplorer:
    restart: unless-stopped
    ports:
      - 32838:32838
    image: nicolasdorier/nbxplorer:2.1.3
    environment:
      NBXPLORER_NETWORK: mainnet
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_NOAUTH: 0
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCUSER: ${BITCOIND_RPC_USER}
      NBXPLORER_BTCRPCPASSWORD: ${BITCOIND_RPC_PASS}
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
      NBXPLORER_RMQHOST: rabbitmq
      NBXPLORER_RMQVIRTUAL: /
      NBXPLORER_RMQUSER: guest
      NBXPLORER_RMQPASS: guest
      NBXPLORER_RMQTRANEX: NewTransaction
      NBXPLORER_RMQBLOCKEX: NewBlock
    volumes:
      - "${DATADIR_ROOT}/.nbxplorer:/datadir"
      - "${DATADIR_ROOT}/.bitcoin:/root/.bitcoin"
      - "${DATADIR_ROOT}/.elements:/root/.elements"
    links:
      - bitcoind
      - rabbitmq

  lightningd:
    image: blockstream/lightningd:prom
    command:
      - lightningd
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=${BITCOIND_RPC_USER}
      - --bitcoin-rpcpassword=${BITCOIND_RPC_PASS}
      - --bitcoin-rpcport=43782
      - --network=bitcoin
      - --plugin-dir=/usr/local/bin/plugins
      - --alias=jem2323-lighningd1
      - --log-level=debug
      - --lightning-dir=/root/.lightning
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735" # server port
      - "9835" # api port
      - "9900" # prometheus plugin
    ports:
      - "0.0.0.0:9999:9735"
      - "0.0.0.0:9835:9835"
      - "0.0.0.0:9900:9900"
    links:
      - bitcoind
    volumes:
      - "${DATADIR_ROOT}/.lightningd:/root/.lightning"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      "RABBITMQ_DEFAULT_PASS": "guest"
      "RABBITMQ_DEFAULT_USER": "guest"
      "RABBITMQ_DEFAULT_VHOST": "/"
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672

  lightningd_spark:
    image: shesek/spark-wallet:0.2.9-standalone
    restart: unless-stopped
    environment:
      NETWORK: mainnet
      SPARK_OPT: --no-tls -C /data/.cookie
    command:
      - spark-wallet -l /etc/lightning
      - --login ${SPARK_WALLET_USER}:${SPARK_WALLET_PASS}
    volumes:
    - "${DATADIR_ROOT}/.lightningd:/etc/lightning"
    - "${DATADIR_ROOT}/.lightningd_spark:/data"
    links:
    - lightningd
    ports:
      - "9737:9737"

  electrs:
    image: joemphilips/electrs:v0.8.2
    restart: unless-stopped
    user: root:root
    environment:
      RUST_BACKTRACE: 1
    command:
      - electrs
      - -vvv
      - --network=bitcoin
      - --db-dir=/data
      - --daemon-dir=/bitcoin
      - --electrum-rpc-addr=127.0.0.1:50001
      - --daemon-rpc-addr=bitcoind:43782
      - --monitoring-addr=electrs:4224
      - --bulk-index-threads=1
      - --tx-cache-size-mb=256
    volumes:
      - "${DATADIR_ROOT}/.electrs/data:/data"
      - "${DATADIR_ROOT}/.electrs/etc:/etc/electrs"
      - "${DATADIR_ROOT}/.bitcoin:/bitcoin"
    ports:
      - 50001:50001
    expose:
      - "4224" # for prometheus

  esplora:
    image: joemphilips/esplora:git-1479936
    environment:
      NODE_ENV: production
    entrypoint: bash -c
    command:
      - /srv/explorer/run.sh bitcoin-mainnet explorer
    ports:
      - 8082:80
    volumes:
      - "${DATADIR_ROOT}/.bitcoin:/data"

  alertmanager:
    image: prom/alertmanager:v0.20.0
    user: root:root
    restart: unless-stopped
    command:
      - '--config.file=/alertmanager.yml'
      - '--storage.path=/data'
    volumes:
      - './prometheus/etc/alertmanager.yml:/alertmanager.yml:ro'
      - '${DATADIR_ROOT}/prometheus/data/alertmanager:/data'
    expose:
      - "9093"

  prometheus:
    image: prom/prometheus:v2.15.1
    user: root:root
    restart: unless-stopped
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - "./prometheus/etc/prometheus.yml:/prometheus.yml:ro"
      - "./prometheus/etc/alerts.yml:/config/alerts.yml:ro"
      - "${DATADIR_ROOT}/prometheus/data/prometheus:/data"
    links:
      - lightningd
      - alertmanager
      - electrs
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:6.5.2-ubuntu
    ports:
      - 3000:3000
    volumes:
      - "${DATADIR_ROOT}/grafana/data:/var/lib/grafana"
      - "${DATADIR_ROOT}/grafana/provisioning:/etc/grafana/provisioning"
    links:
      - prometheus

  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "./data/postgres:/var/lib/postgresql/data"

