global:
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
  - job_name: lightningd
    scrape_interval: 5s
    static_configs:
      - targets:
        - "lightningd:9900"
