groups:
- name: c-lightning.rules
  rules:
  - alert: c_lightning_node_down
    expr: lightning_node_info{job="lightningd"} == 0
    for: 1m
    labels:
      term: c-lightning
      severity: urgent
    annotations:
      summary: 'c-lightning node is down'
      description: |
        c-lightning node is down. Wake up!
  - alert: c_lighting_has_no_peers
    expr: absent(lightning_peer_connected) == 1
    for: 1m
    labels:
      team: c-lightning
      severity: urgent
    annotations:
      summary: 'c-lightning has no peers'
      description: |
        c-lightning node has no connections to other peers. You may want to look into why this is so (e.g. firewall problems, internet conectivity, etc)
