global:
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: noreply@bitcoin-sandbox-alertmanager.com
  smtp_auth_username: "joemphilips@gmail.com"
  smtp_auth_identity: "joemphilips@gmail.com"
  smtp_auth_password: "wrzlwibspruxuxxn"

# The root route on which each incoming alert enters.
route:
  group_by: ['alertname']
  # When a new group of alerts is created by an incoming alert, wait at least
  # 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # lf new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeatinterval' to
  # resend them.
  repeat_interval: 20m
  receiver: 'alerts-email'
receivers:
  - name: alerts-email
    email_configs:
    - to: joemphilips@gmail.com

