global:
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files:
  - /config/alerts.yml

alerting:
  alertmanagers:
  # - scheme: http
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: lightningd
    scrape_interval: 5s
    static_configs:
      - targets:
        - "lightningd:9900"
  - job_name: electrs
    scrape_interval: 10s
    static_configs:
      - targets:
        - "electrs:4224"
